# Generated by Django 5.2.6 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/'),
        ),
    ]
