# Generated by Django 5.2.6 on 2025-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
